### PR TITLE
Fix QReader model not present 

### LINKED ISSUE #3: Ensure QReader ML model is downloaded during container build
As we discovered during our test on last tuesday, we need to ensure the the ML Model necessary for the QReader library that is used in the qr code scanner node is present in the docker container to avoid the library trying to download the aforementioned ML model during runtime.

### PR DESCRIPTION
**Pull request by J0hn-Lawrence**
This PR closes #3 , see the issue for details.

### CODE REVIEW

**Review by finn-ehlers — APPROVED** [review]
Thanks for adding <3

**Comment by Philipp66904** [comment]
Did you recreate this functionality or have you copied it from the drone? @J0hn-Lawrence

**Comment by J0hn-Lawrence** [comment]
> Did you recreate this functionality or have you copied it from the drone? @J0hn-Lawrence

Recreated from my memory of what we did on the drone, but I am 99% certain it is correct. What do you think @Finndows ?

**Review by Philipp66904 — APPROVED** [review]
Looks good

**Comment by finn-ehlers** [comment]
> > Did you recreate this functionality or have you copied it from the drone? @J0hn-Lawrence
> 
> Recreated from my memory of what we did on the drone, but I am 99% certain it is correct. What do you think @Finndows ?

Yes, looks good

**Comment by Philipp66904** [comment]
FYI: I tested the `download_qreader_model.py` script first with internet connection and then without and it still worked. So our software shouldn't need internet for running.

@J0las @di-math

**Comment by J0hn-Lawrence** [comment]
> FYI: I tested the `download_qreader_model.py` script first with internet connection and then without and it still worked. So our software shouldn't need internet for running.
> 
> @J0las @di-math

I am a bit confused. Are you saying it worked and the script downloaded the model the first time and was then able to use this downloaded model in the second run? If so, then that is good.

**Comment by finn-ehlers** [comment]
> FYI: I tested the `download_qreader_model.py` script first with internet connection and then without and it still worked. So our software shouldn't need internet for running.
> 
> @J0las @di-math

How can that script work without internet connection? It needs to have the weights downloaded to work which it does using it for the first time. Did you delete the weights manually / tested it in the container or how did you assure that it worked without internet? i think we need internet when building the docker at the moment.

**Comment by J0hn-Lawrence** [comment]
> > FYI: I tested the `download_qreader_model.py` script first with internet connection and then without and it still worked. So our software shouldn't need internet for running.
> > @J0las @di-math
> 
> How can that script work without internet connection? It needs to have the weights downloaded to work which it does using it for the first time. Did you delete the weights manually / tested it in the container or how did you assure that it worked without internet? i think we need internet when building the docker at the moment.

That's my understanding as well.

**Comment by Philipp66904** [comment]
Yes, I had internet connection during the first run and it downloaded all the weights. In the second run however, I turned off all internet connections and could still run the script.

We need internet connection during docker builds anyway, so that's not a problem. But it is definitely nice, if we don't need internet access to start the container (which it looks like).

**Comment by finn-ehlers** [comment]
> Yes, I had internet connection during the first run and it downloaded all the weights. In the second run however, I turned off all internet connections and could still run the script.
> 
> We need internet connection during docker builds anyway, so that's not a problem. But it is definitely nice, if we don't need internet access to start the container (which it looks like).

Okay, yeah. Once downloaded it is fine. And as we run it once in the docker build it should have downloaded the weights. My node then doesn't need to dowload them the first time.

Thanks for the test. We should still keep an eye on it saturday

**Pull request merged**
